/********************************************************************
* FEHTesterGUIDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error FEHTesterGUIDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableFEHTesterGUIDict();
extern void G__cpp_setup_inheritanceFEHTesterGUIDict();
extern void G__cpp_setup_typetableFEHTesterGUIDict();
extern void G__cpp_setup_memvarFEHTesterGUIDict();
extern void G__cpp_setup_globalFEHTesterGUIDict();
extern void G__cpp_setup_memfuncFEHTesterGUIDict();
extern void G__cpp_setup_funcFEHTesterGUIDict();
extern void G__set_cpp_environmentFEHTesterGUIDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FEHTesterGUI.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__FEHTesterGUIDictLN_TClass;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TBuffer;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TMemberInspector;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TObject;
extern G__linked_taginfo G__FEHTesterGUIDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_string;
extern G__linked_taginfo G__FEHTesterGUIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TList;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TTimer;
extern G__linked_taginfo G__FEHTesterGUIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TQObject;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TQObjSender;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGWindow;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGObject;
extern G__linked_taginfo G__FEHTesterGUIDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGFrame;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGCompositeFrame;
extern G__linked_taginfo G__FEHTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGTextButton;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGVerticalFrame;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGMainFrame;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGGroupFrame;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TColor;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGLabel;
extern G__linked_taginfo G__FEHTesterGUIDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TThread;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__FEHTesterGUIDictLN_TGTextEntry;
extern G__linked_taginfo G__FEHTesterGUIDictLN_IDList;
extern G__linked_taginfo G__FEHTesterGUIDictLN_FEHTesterGUI;

/* STUB derived class for protected member access */
