//
// File generated by rootcint at Mon Jan 30 19:23:00 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME FEHTesterGUIDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "FEHTesterGUIDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::IDList IDList;
      #else
      class IDList  {
         public:
         //friend XX;
         int nID; //creates unique widget's IDs
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void IDList_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void IDList_Dictionary();
   static void *new_IDList(void *p = 0);
   static void *newArray_IDList(Long_t size, void *p);
   static void delete_IDList(void *p);
   static void deleteArray_IDList(void *p);
   static void destruct_IDList(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::IDList*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::IDList) == sizeof( ::ROOTShadow::Shadow::IDList));
      ::IDList *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::IDList),0);
      static ::ROOT::TGenericClassInfo 
         instance("IDList", "./FEHTesterGUI.h", 46,
                  typeid(::IDList), ::ROOT::DefineBehavior(ptr, ptr),
                  &IDList_ShowMembers, &IDList_Dictionary, isa_proxy, 4,
                  sizeof(::IDList) );
      instance.SetNew(&new_IDList);
      instance.SetNewArray(&newArray_IDList);
      instance.SetDelete(&delete_IDList);
      instance.SetDeleteArray(&deleteArray_IDList);
      instance.SetDestructor(&destruct_IDList);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::IDList*)
   {
      return GenerateInitInstanceLocal((::IDList*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::IDList*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void IDList_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::IDList*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void IntegratedTesterGui_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_IntegratedTesterGui(void *p);
   static void deleteArray_IntegratedTesterGui(void *p);
   static void destruct_IntegratedTesterGui(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::IntegratedTesterGui*)
   {
      ::IntegratedTesterGui *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::IntegratedTesterGui >(0);
      static ::ROOT::TGenericClassInfo 
         instance("IntegratedTesterGui", ::IntegratedTesterGui::Class_Version(), "./FEHTesterGUI.h", 57,
                  typeid(::IntegratedTesterGui), ::ROOT::DefineBehavior(ptr, ptr),
                  &::IntegratedTesterGui::Dictionary, isa_proxy, 4,
                  sizeof(::IntegratedTesterGui) );
      instance.SetDelete(&delete_IntegratedTesterGui);
      instance.SetDeleteArray(&deleteArray_IntegratedTesterGui);
      instance.SetDestructor(&destruct_IntegratedTesterGui);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::IntegratedTesterGui*)
   {
      return GenerateInitInstanceLocal((::IntegratedTesterGui*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::IntegratedTesterGui*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr IntegratedTesterGui::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *IntegratedTesterGui::Class_Name()
{
   return "IntegratedTesterGui";
}

//______________________________________________________________________________
const char *IntegratedTesterGui::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::IntegratedTesterGui*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int IntegratedTesterGui::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::IntegratedTesterGui*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void IntegratedTesterGui::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::IntegratedTesterGui*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *IntegratedTesterGui::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::IntegratedTesterGui*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
namespace ROOTDict {
   void IDList_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class IDList.
      typedef ::ROOTShadow::Shadow::IDList ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::IDList*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nID", &sobj->nID);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_IDList(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::IDList : new ::IDList;
   }
   static void *newArray_IDList(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::IDList[nElements] : new ::IDList[nElements];
   }
   // Wrapper around operator delete
   static void delete_IDList(void *p) {
      delete ((::IDList*)p);
   }
   static void deleteArray_IDList(void *p) {
      delete [] ((::IDList*)p);
   }
   static void destruct_IDList(void *p) {
      typedef ::IDList current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::IDList

//______________________________________________________________________________
void IntegratedTesterGui::Streamer(TBuffer &R__b)
{
   // Stream an object of class IntegratedTesterGui.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(IntegratedTesterGui::Class(),this);
   } else {
      R__b.WriteClassBuffer(IntegratedTesterGui::Class(),this);
   }
}

//______________________________________________________________________________
void IntegratedTesterGui::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class IntegratedTesterGui.
      TClass *R__cl = ::IntegratedTesterGui::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQObject", &fQObject);
      R__insp.InspectMember(fQObject, "fQObject.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fMain", &fMain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEcanvas", &fEcanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEcanvas1", &fEcanvas1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEcanvas2", &fEcanvas2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fEcanvas3", &fEcanvas3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*HorFramePlots", &HorFramePlots);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*VerFramePlots1", &VerFramePlots1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*VerFramePlots2", &VerFramePlots2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fForButtons", &fForButtons);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRadiob[2]", &fRadiob);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fExit", &fExit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fStartTest", &fStartTest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fRedoCalibration", &fRedoCalibration);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fButtonGroup", &fButtonGroup);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "IDs", (void*)&IDs);
      R__insp.InspectMember("IDList", (void*)&IDs, "IDs.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*state", &state);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*SerialNumberLabel", &SerialNumberLabel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*serialNumber", &serialNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TestSummary", &TestSummary);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*EnvMonitoringLabel", &EnvMonitoringLabel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGframe", &fGframe);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGframe2", &fGframe2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGframe3", &fGframe3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGframe4", &fGframe4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*TestSummaryLabel", &TestSummaryLabel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTextEntry", &fTextEntry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*DBStatusLabel", &DBStatusLabel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*timer", &timer);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*testerThread", &testerThread);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "testerDone", &testerDone);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*AlreadyTestedPopUpLabel", &AlreadyTestedPopUpLabel);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPopUp", &fPopUp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPopupTopVertical", &fPopupTopVertical);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fProceed", &fProceed);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fCancelTest", &fCancelTest);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHorFrameForPopUpButtons", &fHorFrameForPopUpButtons);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*serialNumber_char", &serialNumber_char);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "logbook", (void*)&logbook);
      R__insp.InspectMember("ofstream", (void*)&logbook, "logbook.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "envCounter", &envCounter);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrapper around operator delete
   static void delete_IntegratedTesterGui(void *p) {
      delete ((::IntegratedTesterGui*)p);
   }
   static void deleteArray_IntegratedTesterGui(void *p) {
      delete [] ((::IntegratedTesterGui*)p);
   }
   static void destruct_IntegratedTesterGui(void *p) {
      typedef ::IntegratedTesterGui current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::IntegratedTesterGui

/********************************************************
* FEHTesterGUIDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableFEHTesterGUIDict();

extern "C" void G__set_cpp_environmentFEHTesterGUIDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("FEHTesterGUI.h");
  G__cpp_reset_tagtableFEHTesterGUIDict();
}
#include <new>
extern "C" int G__cpp_dllrevFEHTesterGUIDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* IDList */
static int G__FEHTesterGUIDict_474_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   IDList* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new IDList[n];
     } else {
       p = new((void*) gvp) IDList[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new IDList;
     } else {
       p = new((void*) gvp) IDList;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IDList));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_474_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((IDList*) G__getstructoffset())->GetUnID());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__FEHTesterGUIDict_474_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   IDList* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new IDList(*(IDList*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IDList));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef IDList G__TIDList;
static int G__FEHTesterGUIDict_474_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (IDList*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((IDList*) (soff+(sizeof(IDList)*i)))->~G__TIDList();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (IDList*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((IDList*) (soff))->~G__TIDList();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__FEHTesterGUIDict_474_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   IDList* dest = (IDList*) G__getstructoffset();
   *dest = *(IDList*) libp->para[0].ref;
   const IDList& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* IntegratedTesterGui */
static int G__FEHTesterGUIDict_475_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const IntegratedTesterGui*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((IntegratedTesterGui*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((IntegratedTesterGui*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((IntegratedTesterGui*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((IntegratedTesterGui*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((IntegratedTesterGui*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   const int imax = 6, dmax = 8, umax = 50;
   int objsize, type, i, icnt = 0, dcnt = 0, ucnt = 0;
   G__value *pval;
   G__int64 lval[imax] = {0};
   double dval[dmax] = {0};
   union { G__int64 lval; double dval; } u[umax] = {{0}};
   lval[icnt] = G__getstructoffset(); icnt++; // this pointer
   for (i = 0; i < libp->paran; i++) {
      type = G__value_get_type(&libp->para[i]);
      pval = &libp->para[i];
      if (isupper(type))
         objsize = G__LONGALLOC;
      else
         objsize = G__sizeof(pval);
      switch (type) {
         case 'c': case 'b': case 's': case 'r': objsize = sizeof(int); break;
         case 'f': objsize = sizeof(double); break;
      }
#ifdef G__VAARG_PASS_BY_REFERENCE
      if (objsize > G__VAARG_PASS_BY_REFERENCE) {
         if (pval->ref > 0x1000) {
            if (icnt < imax) {
               lval[icnt] = pval->ref; icnt++;
            } else {
               u[ucnt].lval = pval->ref; ucnt++;
            }
         } else {
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            }
         }
         type = 'z';
      }
#endif
      switch (type) {
         case 'n': case 'm':
            if (icnt < imax) {
               lval[icnt] = (G__int64)G__Longlong(*pval); icnt++;
            } else {
               u[ucnt].lval = (G__int64)G__Longlong(*pval); ucnt++;
            } break;
         case 'f': case 'd':
            if (dcnt < dmax) {
               dval[dcnt] = G__double(*pval); dcnt++;
            } else {
               u[ucnt].dval = G__double(*pval); ucnt++;
            } break;
         case 'z': break;
         case 'u':
            if (objsize >= 16) {
               memcpy(&u[ucnt].lval, (void*)pval->obj.i, objsize);
               ucnt += objsize/8;
               break;
            }
            // objsize < 16 -> fall through
         case 'g': case 'c': case 'b': case 'r': case 's': case 'h': case 'i':
         case 'k': case 'l':
         default:
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            } break;
      }
      if (ucnt >= 50) printf("EmitVA: more than 56 var args\n");
   }
      ((IntegratedTesterGui*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), dval[0], dval[1], dval[2], dval[3], dval[4], dval[5], dval[6], dval[7], lval[3], lval[4], lval[5], u[0].lval, u[1].lval, u[2].lval, u[3].lval, u[4].lval, u[5].lval, u[6].lval, u[7].lval, u[8].lval, u[9].lval, u[10].lval, u[11].lval, u[12].lval, u[13].lval, u[14].lval, u[15].lval, u[16].lval, u[17].lval, u[18].lval, u[19].lval, u[20].lval, u[21].lval, u[22].lval, u[23].lval, u[24].lval, u[25].lval, u[26].lval, u[27].lval, u[28].lval, u[29].lval, u[30].lval, u[31].lval, u[32].lval, u[33].lval, u[34].lval, u[35].lval, u[36].lval, u[37].lval, u[38].lval, u[39].lval, u[40].lval, u[41].lval, u[42].lval, u[43].lval, u[44].lval, u[45].lval, u[46].lval, u[47].lval, u[48].lval, u[49].lval);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   IntegratedTesterGui* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new IntegratedTesterGui(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) IntegratedTesterGui(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((IntegratedTesterGui*) G__getstructoffset())->hybridAlreadyTested());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->TranslateReturnValue((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->DisactivateTestButton();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->ActivateTestButton();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->DoExit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->DoDraw((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->integratedtester();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->WriteInfo(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((IntegratedTesterGui*) G__getstructoffset())->returnDateAndTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         string* pobj;
         string xobj = ((IntegratedTesterGui*) G__getstructoffset())->ReadCompleteFile(*((string*) G__int(libp->para[0])));
         pobj = new string(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->WriteResultsTestToDB((int) G__int(libp->para[0]), *((string*) G__int(libp->para[1]))
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->SetGroupEnabled((Bool_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->UpdateEnvMonitoring();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->launchThread();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->UpdateSerNumberLabel();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) IntegratedTesterGui::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) IntegratedTesterGui::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) IntegratedTesterGui::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      IntegratedTesterGui::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((IntegratedTesterGui*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) IntegratedTesterGui::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) IntegratedTesterGui::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) IntegratedTesterGui::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__FEHTesterGUIDict_475_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) IntegratedTesterGui::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef IntegratedTesterGui G__TIntegratedTesterGui;
static int G__FEHTesterGUIDict_475_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (IntegratedTesterGui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((IntegratedTesterGui*) (soff+(sizeof(IntegratedTesterGui)*i)))->~G__TIntegratedTesterGui();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (IntegratedTesterGui*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((IntegratedTesterGui*) (soff))->~G__TIntegratedTesterGui();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */
static int G__FEHTesterGUIDict__0_2501(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 89, (long) runThreadFunc((void*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/* IDList */

/* IntegratedTesterGui */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncFEHTesterGUIDict {
 public:
  G__Sizep2memfuncFEHTesterGUIDict(): p(&G__Sizep2memfuncFEHTesterGUIDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncFEHTesterGUIDict::*p)();
};

size_t G__get_sizep2memfuncFEHTesterGUIDict()
{
  G__Sizep2memfuncFEHTesterGUIDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceFEHTesterGUIDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui))) {
     IntegratedTesterGui *G__Lderived;
     G__Lderived=(IntegratedTesterGui*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui),G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui),G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui),G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui),G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui),G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui),G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui),G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableFEHTesterGUIDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 8 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 8 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* IDList */
static void G__setup_memvarIDList(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IDList));
   { IDList *p; p=(IDList*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"nID=",0,"creates unique widget's IDs");
   }
   G__tag_memvar_reset();
}


   /* IntegratedTesterGui */
static void G__setup_memvarIntegratedTesterGui(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui));
   { IntegratedTesterGui *p; p=(IntegratedTesterGui*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGMainFrame),-1,-1,4,"fMain=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TRootEmbeddedCanvas),-1,-1,4,"fEcanvas3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGHorizontalFrame),-1,-1,4,"HorFramePlots=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGVerticalFrame),-1,-1,4,"VerFramePlots1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGVerticalFrame),-1,-1,4,"VerFramePlots2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGVerticalFrame),-1,-1,4,"fForButtons=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGRadioButton),-1,-1,4,"fRadiob[2]=",0,"Radio buttons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGTextButton),-1,-1,4,"fExit=",0,"Exit text button");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGTextButton),-1,-1,4,"fStartTest=",0,"Calibration text button");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGTextButton),-1,-1,4,"fRedoCalibration=",0,"Text button to redo the calibration for the current hybrid");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGVButtonGroup),-1,-1,4,"fButtonGroup=",0,"Button group");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IDList),-1,-1,4,"IDs=",0,"Widget IDs generator");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGLabel),-1,-1,4,"state=",0,"Label showing the state of the test");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGLabel),-1,-1,4,"SerialNumberLabel=",0,"Label showing the serial number of the hybrid that was scanned");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGLabel),-1,-1,4,"serialNumber=",0,"label showing the SerialNumber of the hybrid. This number is read from a file serial_number.txt");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGLabel),-1,-1,4,"TestSummary=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGLabel),-1,-1,4,"EnvMonitoringLabel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGGroupFrame),-1,-1,4,"fGframe=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGGroupFrame),-1,-1,4,"fGframe2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGGroupFrame),-1,-1,4,"fGframe3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGGroupFrame),-1,-1,4,"fGframe4=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGLabel),-1,-1,4,"TestSummaryLabel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGTextEntry),-1,-1,4,"fTextEntry=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGLabel),-1,-1,4,"DBStatusLabel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TTimer),-1,-1,4,"timer=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TThread),-1,-1,4,"testerThread=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"testerDone=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGLabel),-1,-1,4,"AlreadyTestedPopUpLabel=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGMainFrame),-1,-1,4,"fPopUp=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGVerticalFrame),-1,-1,4,"fPopupTopVertical=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGTextButton),-1,-1,4,"fProceed=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGTextButton),-1,-1,4,"fCancelTest=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TGHorizontalFrame),-1,-1,4,"fHorFrameForPopUpButtons=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->serialNumber_char)-(long)(p)),67,0,1,-1,-1,-1,1,"serialNumber_char=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->logbook)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR),G__defined_typename("ofstream"),-1,1,"logbook=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->envCounter)-(long)(p)),105,0,0,-1,-1,-1,1,"envCounter=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarFEHTesterGUIDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncIDList(void) {
   /* IDList */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IDList));
   G__memfunc_setup("IDList",553,G__FEHTesterGUIDict_474_0_1, 105, G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IDList), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetUnID",624,G__FEHTesterGUIDict_474_0_2, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("IDList", 553, G__FEHTesterGUIDict_474_0_3, (int) ('i'), G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IDList), -1, 0, 1, 1, 1, 0, "u 'IDList' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~IDList", 679, G__FEHTesterGUIDict_474_0_4, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__FEHTesterGUIDict_474_0_5, (int) ('u'), G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IDList), -1, 1, 1, 1, 1, 0, "u 'IDList' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncIntegratedTesterGui(void) {
   /* IntegratedTesterGui */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui));
   G__memfunc_setup("GetListOfSignals",1602,G__FEHTesterGUIDict_475_0_1, 85, G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__FEHTesterGUIDict_475_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__FEHTesterGUIDict_475_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("LowPriority",1172,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("EmitVA",550,G__FEHTesterGUIDict_475_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__FEHTesterGUIDict_475_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,(G__InterfaceMethod) NULL,121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ChangedBy",869,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Message",709,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IntegratedTesterGui",1955,G__FEHTesterGUIDict_475_0_26, 105, G__get_linked_tagnum(&G__FEHTesterGUIDictLN_IntegratedTesterGui), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("hybridAlreadyTested",1965,G__FEHTesterGUIDict_475_0_27, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TranslateReturnValue",2091,G__FEHTesterGUIDict_475_0_28, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DisactivateTestButton",2189,G__FEHTesterGUIDict_475_0_29, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ActivateTestButton",1869,G__FEHTesterGUIDict_475_0_30, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoExit",589,G__FEHTesterGUIDict_475_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoDraw",577,G__FEHTesterGUIDict_475_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("integratedtester",1726,G__FEHTesterGUIDict_475_0_33, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("WriteInfo",919,G__FEHTesterGUIDict_475_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("returnDateAndTime",1728,G__FEHTesterGUIDict_475_0_35, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadCompleteFile",1589,G__FEHTesterGUIDict_475_0_36, 117, G__get_linked_tagnum(&G__FEHTesterGUIDictLN_string), -1, 0, 1, 1, 1, 0, "u 'string' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("WriteResultsTestToDB",2022,G__FEHTesterGUIDict_475_0_37, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - - u 'string' - 0 - - "
"i - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetGroupEnabled",1508,G__FEHTesterGUIDict_475_0_38, 121, -1, -1, 0, 1, 1, 1, 0, "g - 'Bool_t' 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateEnvMonitoring",1970,G__FEHTesterGUIDict_475_0_39, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("launchThread",1235,G__FEHTesterGUIDict_475_0_40, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("UpdateSerNumberLabel",2006,G__FEHTesterGUIDict_475_0_41, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__FEHTesterGUIDict_475_0_42, 85, G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&IntegratedTesterGui::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__FEHTesterGUIDict_475_0_43, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IntegratedTesterGui::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__FEHTesterGUIDict_475_0_44, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&IntegratedTesterGui::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__FEHTesterGUIDict_475_0_45, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&IntegratedTesterGui::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__FEHTesterGUIDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__FEHTesterGUIDict_475_0_49, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__FEHTesterGUIDict_475_0_50, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IntegratedTesterGui::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__FEHTesterGUIDict_475_0_51, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IntegratedTesterGui::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__FEHTesterGUIDict_475_0_52, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&IntegratedTesterGui::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__FEHTesterGUIDict_475_0_53, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&IntegratedTesterGui::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~IntegratedTesterGui", 2081, G__FEHTesterGUIDict_475_0_54, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncFEHTesterGUIDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {
   G__memvar_setup((void*)(&dataBasePath),67,0,1,-1,-1,-1,1,"dataBasePath=",0,(char*)NULL);
   G__memvar_setup((void*)(&serialNumberPath),67,0,1,-1,-1,-1,1,"serialNumberPath=",0,(char*)NULL);
   G__memvar_setup((void*)(&logPath),67,0,1,-1,-1,-1,1,"logPath=",0,(char*)NULL);

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalFEHTesterGUIDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
   G__memfunc_setup("runThreadFunc", 1337, G__FEHTesterGUIDict__0_2501, 89, -1, -1, 0, 1, 1, 1, 0, "Y - - 0 - -", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcFEHTesterGUIDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__FEHTesterGUIDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR = { "basic_ofstream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TTimer = { "TTimer" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGHorizontalFrame = { "TGHorizontalFrame" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGGroupFrame = { "TGGroupFrame" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGRadioButton = { "TGRadioButton" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGVButtonGroup = { "TGVButtonGroup" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TThread = { "TThread" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_IDList = { "IDList" , 99 , -1 };
G__linked_taginfo G__FEHTesterGUIDictLN_IntegratedTesterGui = { "IntegratedTesterGui" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableFEHTesterGUIDict() {
  G__FEHTesterGUIDictLN_TClass.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TBuffer.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TMemberInspector.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TObject.tagnum = -1 ;
  G__FEHTesterGUIDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_string.tagnum = -1 ;
  G__FEHTesterGUIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TList.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TTimer.tagnum = -1 ;
  G__FEHTesterGUIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TQObject.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TQObjSender.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGWindow.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGObject.tagnum = -1 ;
  G__FEHTesterGUIDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGFrame.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGCompositeFrame.tagnum = -1 ;
  G__FEHTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGTextButton.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGVerticalFrame.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGHorizontalFrame.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGMainFrame.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGGroupFrame.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGRadioButton.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGLabel.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGVButtonGroup.tagnum = -1 ;
  G__FEHTesterGUIDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TThread.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__FEHTesterGUIDictLN_TGTextEntry.tagnum = -1 ;
  G__FEHTesterGUIDictLN_IDList.tagnum = -1 ;
  G__FEHTesterGUIDictLN_IntegratedTesterGui.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableFEHTesterGUIDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_string);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TList);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TTimer);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGHorizontalFrame);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGGroupFrame);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGRadioButton);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGVButtonGroup);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TThread);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_TGTextEntry);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_IDList),sizeof(IDList),-1,263424,(char*)NULL,G__setup_memvarIDList,G__setup_memfuncIDList);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__FEHTesterGUIDictLN_IntegratedTesterGui),sizeof(IntegratedTesterGui),-1,324608,(char*)NULL,G__setup_memvarIntegratedTesterGui,G__setup_memfuncIntegratedTesterGui);
}
extern "C" void G__cpp_setupFEHTesterGUIDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupFEHTesterGUIDict()");
  G__set_cpp_environmentFEHTesterGUIDict();
  G__cpp_setup_tagtableFEHTesterGUIDict();

  G__cpp_setup_inheritanceFEHTesterGUIDict();

  G__cpp_setup_typetableFEHTesterGUIDict();

  G__cpp_setup_memvarFEHTesterGUIDict();

  G__cpp_setup_memfuncFEHTesterGUIDict();
  G__cpp_setup_globalFEHTesterGUIDict();
  G__cpp_setup_funcFEHTesterGUIDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncFEHTesterGUIDict();
  return;
}
class G__cpp_setup_initFEHTesterGUIDict {
  public:
    G__cpp_setup_initFEHTesterGUIDict() { G__add_setup_func("FEHTesterGUIDict",(G__incsetup)(&G__cpp_setupFEHTesterGUIDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initFEHTesterGUIDict() { G__remove_setup_func("FEHTesterGUIDict"); }
};
G__cpp_setup_initFEHTesterGUIDict G__cpp_setup_initializerFEHTesterGUIDict;

