/********************************************************************
* IntegratedTesterGUIDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error IntegratedTesterGUIDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableIntegratedTesterGUIDict();
extern void G__cpp_setup_inheritanceIntegratedTesterGUIDict();
extern void G__cpp_setup_typetableIntegratedTesterGUIDict();
extern void G__cpp_setup_memvarIntegratedTesterGUIDict();
extern void G__cpp_setup_globalIntegratedTesterGUIDict();
extern void G__cpp_setup_memfuncIntegratedTesterGUIDict();
extern void G__cpp_setup_funcIntegratedTesterGUIDict();
extern void G__set_cpp_environmentIntegratedTesterGUIDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "IntegratedTesterGUI.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TClass;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TBuffer;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TMemberInspector;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TObject;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_basic_ofstreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_string;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TList;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TQObject;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TQObjSender;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGWindow;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGObject;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGFrame;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGCompositeFrame;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGTextButton;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGVerticalFrame;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGHorizontalFrame;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGMainFrame;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGGroupFrame;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGRadioButton;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGLabel;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGVButtonGroup;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_TGTextEntry;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_IDList;
extern G__linked_taginfo G__IntegratedTesterGUIDictLN_IntegratedTesterGui;

/* STUB derived class for protected member access */
